info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  mail:
    host: smtp.gmail.com
    port: 587
    username: renuka17112001@gmail.com
    password: aoglyzqqufvdggmx
    props:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
  controllers:
    defaultScope: singleton
dataSource:
  dbCreate: update
  url: jdbc:mysql://localhost:3306/budget_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: Renuka@123
  dialect: org.hibernate.dialect.MySQL8Dialect

hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
